server:
  port: 8082

spring:
  application:
    name: apptest

  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          service-url: http://localhost:8082

  management:
    endpoints:
      web:
        exposure:
          include: "*"
