spring:
  application:
    name: Gateway
  cloud: 
    discovery:
      enabled: false    
      client:
        health-indicator:
          enabled: false  
  boot:
    admin:
      client:
        url: http://bootadmin.private.kpaasta.kr
        username: admin
        password: admin
        instance:
          service-url: http://gateway.kpaasta.kr

health:
  config:
    enabled: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans, heapdump, threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
