server:
  port: 8083
  
spring:
  application:
    name: gateway

  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          service-url: http://localhost:8083

health:
  config:
    enabled: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans, heapdump, threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
