server:
  port: 8083
  
spring:
  application:
    name: Gateway

  cloud: 
    gateway:
      routes:
        - id: apptest_greeting
          url: http://localhost:8082
          predicates:
            - Path=/greeting  
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          service-url: http://localhost:8083

health:
  config:
    enabled: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans, heapdump, threaddump
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
